### ISSUE TITLE
String::Length missing

### ISSUE THREAD

**Issue by sampsongao** [nodejs/node-api#14]
Is there any reason why we don't have Length method for Napi::String?

**Comment by jasongin** [comment]
Most of the time what you want is the length of the utf8 or utf16 encoding:  `value.Utf8Value().size()` or `value.Utf16Value().size()`.

Maybe there should be a `Napi::String::Length()` method that calls `napi_get_value_string_length()` to get the character length. Or maybe we should remove `napi_get_value_string_length()`, since it's not very useful and a potential source of localization bugs if it is used incorrectly.

**Comment by jasongin** [comment]
See https://github.com/nodejs/abi-stable-node/issues/226 about removing `napi_get_value_string_length()`.

**Comment by jasongin** [comment]
Closing because `napi_get_value_string_length()` was removed in https://github.com/nodejs/node/pull/12496
